### ISSUE TITLE
Disable extension pop up notifications? Add a FAQ and an entry about fixing redirects to 127.0.0.1? Maybe also modify the pop up window with an explanation if the detected attack targets localhost?

### ISSUE THREAD

**Issue by winteriscariot** [polcak/jsrestrictor#125]
I'm not seeing the option in the extension settings. Am I missing it? Is there a way to disable pop up notifications of blocked things? It happens frequently and is quite annoying, I don't need to know every time something is blocked.

**Comment by kevxyz** [comment]
Agree - it should operate like uBlock Origin. Stay quiet but give the option to show a flag on the extension icon that shows how much JS is getting blocked on page.

**Comment by polcak** [comment]
There is currently not an option to silence notifications, we should add such option.

**Comment by polcak** [comment]
See #130. It might be worth not notifying connections to 0.0.0.0 by default.

**Comment by polcak** [comment]
Hello Tealk,

$ host amazon.de
amazon.de has address 176.32.108.185
amazon.de has address 52.95.120.34
amazon.de has address 54.239.39.102

$ host fls-eu.amazon.de
fls-eu.amazon.de is an alias for fls-eu.amazon.com.
fls-eu.amazon.com is an alias for gateway.prod.eu-west-1.forester.a2z.com.
gateway.prod.eu-west-1.forester.a2z.com is an alias for endpoint.prod.eu-west-1.forester.a2z.com.
endpoint.prod.eu-west-1.forester.a2z.com has address 63.32.252.108
endpoint.prod.eu-west-1.forester.a2z.com has address 52.30.141.39
endpoint.prod.eu-west-1.forester.a2z.com has address 52.50.251.175
endpoint.prod.eu-west-1.forester.a2z.com has address 52.48.132.20
endpoint.prod.eu-west-1.forester.a2z.com has address 52.19.1.0
endpoint.prod.eu-west-1.forester.a2z.com has address 54.194.65.3
endpoint.prod.eu-west-1.forester.a2z.com has address 52.212.5.217
endpoint.prod.eu-west-1.forester.a2z.com has address 54.77.181.165

There seems to be something broken with your DNS. What IP addresses does your resolver return?

**Comment by Tealk** [comment]
for the host command needs to install bind @polcak ?

`PING amazon.de (52.95.120.34) 56(84) bytes of data.`

can it be that the Adguard Home makes there problems?
`PING fls-eu.amazon.de (127.0.0.1) 56(84) bytes of data.`

**Comment by polcak** [comment]
Please, see https://github.com/polcak/jsrestrictor/issues/130#issuecomment-935682628. I do not know what Adguard Home is but if it modifies DNS replies, it may be responsible. I suggest that you try to locate the service that modifies DNS a configure it to use 0.0.0.0 instead of 127.0.0.1.

General: When thinking about these issues, I am inclined to think that the current behaviour identifies problems in set up, so it seems to be beneficial that there is no option to mute. Maybe a FAQ entry could be more appropriate?

**Comment by Tealk** [comment]
I do not know what Adguard Home is but if it modifies DNS replies, it may be responsible. I suggest that you try to locate the service that modifies DNS a configure it to use 0.0.0.0 instead of 127.0.0.1.
> 

Adguard Home is like pihole an ad-block on dns basis. https://github.com/AdguardTeam/AdGuardHome
unfortunately i can't influence how it works; but the people i know who care about privacy all use a dns adblock

**Comment by rhz** [comment]
I'd like to see an option to mute notifications entirely or only see the first notification from each tab. I'm getting infinitely many notifications from [mega.nz](https://mega.nz/) for the network boundary shield.

**Comment by UwUnyaa** [comment]
I think a per-domain toggle would be nice. Some websites trigger the boundary shield countless times per visit, and being able to just add a rule that I want to allow all or deny all would make the experience much smoother. Not to mention that certain websites end up spitting out countless notifications (especially steam chat).

**Comment by polcak** [comment]
Related https://pagure.io/JShelter/webextension/issue/21

**Comment by polcak** [comment]
0.8 will provide an option to turn NBS notifications off. There will not be a per-site settings, yet. There might be a bug causing some notifications to evade the settings that will be fixed in later versions. I do not thing that it is a blocker for a release containing other functionality.

**Comment by polcak** [comment]
Per-domain toggling https://pagure.io/JShelter/webextension/issue/63

There will be a FAQ entry, we added explanations to the UI. There should also be an option to have working FPD with no notification soon. I am closing the issue. Feel free to comment if I missed something.
