### ISSUE TITLE
Suggestion: mute Network Shield notifications for social networks

### ISSUE THREAD

**Issue by eleius** [polcak/jsrestrictor#130]
I see lots of notifications from Network Shield blocking connection requests to Facebook. Since they're embedded in many websites, it would be nice to have an option to mute notifications for social networks.

**Comment by polcak** [comment]
You should not see NBS notifications for such configuration. JSR does not protect from trackers. What is the Origin of the page, what is the Facebook domain and its IP address (by any chance, do you use a DNS-based blocker)?

**Comment by polcak** [comment]
See https://polcak.github.io/jsrestrictor/blogarticles/localportscanning.html for an example how NBS should work. In your set up, you insert the vulnerability by letting the page connect to localhost instead of the real server. I suggest you change localhost/127.0.0.1 in your /etc/hosts to 0.0.0.0.

For now, I see this as duplicate of #125.

**Comment by eleius** [comment]
Thanks, I replaced 127.0.0.1 in my hosts file.
