### ISSUE TITLE
Freeze on youtube videos/twitch streams when opening new site

### ISSUE THREAD

**Issue by brochard** [polcak/jsrestrictor#144]
Hi,
almost everytime I open a (big) site, my youtube video/twitch stream freeze for a short moment, if I open multiple windows it freezes multiple times.
I'm on default settings, using firefox and it doesn't happen without the extension installed.

**Comment by polcak** [comment]
We should try to reproduce the issue

**Comment by polcak** [comment]
I cannot reproduce. I tried on a computer without audio so I am not sure about the audio output. I tried Firefox and JShelter 0.9. I opened youtube.com and opened a video. I opened another window and loaded cnn.com. I reload the page. I opened bbc.com. There was no visible lag in the video. Did the speed improve for you? If yes, please, tell us.

If not, please, provide more details:

## Summary

[Explain your issues, be concrete, what is wrong and why. Make sure that you explain yourself and
the text is clear and understandable. Explain what exactly you mean by freeze. Do I need audio?]

## Setup

OS: 
Browser: 
JShelter Version: 
Other extensions that might affect JShelter behaviour: 

Pages affected: [URL/all pages/URLs]

## How to reproduce

1. ...
2. ...
3. ...

## Expected result

[Fill in what you expected]

## Actual result

[Fill in what happened]

## Reproducibility

[Have you tried another profile/browser/machine/OS?]

## Workarounds

[Have you tried tweaking the extension, e.g. JS Shield. Were you successful? Please create a new custom level and apply it as default, try to add/remove wrapper groups so that different features are wrapped. Try to reproduce the issue. Please, let us know your observations. ]

## Have you tried other steps to solve the issue?

1. I tried X but ...
2. I tried Y but ...
3. I tried Z but ...

[Was there any progress?]

## Additional information / notes

[Other additional notes]

**Comment by brochard** [comment]
I had the addon disabled for this reason
I tested it again (without modifications) and it looks like this problem is fixed !
