### ISSUE TITLE
Specific domain level configuration: Make it possible to export/import configuration files

### ISSUE THREAD

**Issue by davidhedlund** [polcak/jsrestrictor#159]
[Cookie AutoDelete](https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/) has capabilities to export/import site specific configurations to JSON.

I routinely delete my browser profiles when I encounter site issues with add-ons, so it's not convenient to config the sites over and over in JavaScript Restrictor. I strongly advise you to implement my suggested feature, you will have more users in return.

**Comment by polcak** [comment]
Coincidentally, we have a similar feature for development and debugging purposes. The functionality is in the source code but not released to AMO and Chrome Store. It will be a part of the next release.

So far you need to double click on the crab logo to enable the UI. However, as you said, this might be beneficial for import/export. To enable for all users, we will need to create import checks so that all necessary parameters are set.

**Comment by polcak** [comment]
If you want to build from source, follow https://polcak.github.io/jsrestrictor/build.html

**Comment by davidhedlund** [comment]
> Coincidentally, we have a similar feature for development and debugging purposes. The functionality is in the source code but not released to AMO and Chrome Store. It will be a part of the next release.
> 
> So far you need to double click on the crab logo to enable the UI. However, as you said, this might be beneficial for import/export. To enable for all users, we will need to create import checks so that all necessary parameters are set.

Thank you very much!

**Comment by polcak** [comment]
This will be released in 0.6
