### ISSUE TITLE
Discussion on WebGL, Plugins, Fonts, Timestamps, Geolocation and other wrappers

### ISSUE THREAD

**Issue by Kees1958** [polcak/jsrestrictor#166]
When using JShelter on max

1. The unmased vendor and renderer return random (invalid) values [see link at MT: [https://malwaretips.com/attachments/1642245908077-png.263592/](https://malwaretips.com/attachments/1642245908077-png.263592/)

2. Plugin has option to provide to fake plugins, but it is better to provide defaults for all Chromium based browsers, Firefox and Safari

3. Fonts, better to provide the standard fonts for the Operating System (Windows, Apple, etc)

**Comment by xsalon** [comment]
Vendor and Renderer are also random on recommended (2) level. According to JShelter blog, these values should be randomized only for maximum protection level.

**Comment by Kees1958** [comment]
No those specific valuee should NOT be randomized, but have real world values, to hide in the herd. Randomizing the MENTIONED values makes you easier to track.

**Comment by Kees1958** [comment]
When you don't understand that these two values should be randomised with REAL values, I give up

**Comment by polcak** [comment]
Hello Kees,

first of all, thank you for reporting the issue. It is indeed an issue that needs to be evaluated and very likely re-evaluated in the future.

JSR/JShelter is a experimental addon and research project. You cannot expect that we will support the extension 24/7. Additionally, have you provided any code that you seem to be so upset?

So let me go through your posts.

I am not sure what exactly you mean by running JShelter on max. I think that you probably mean level 3.

For now, I do not recommend using level 3 if you're most concern about being fingerprintable. See https://jshelter.org/fingerprinting/. Level 3 basically tries to limit access to the real information. The original idea behind the level was to create a unified fingerprint. But I think that if you want a unified fingerprint, you need to go to Torbrowser. That way you use the same configuration as all other people using Torbrowser (or maybe a part with similar HW). That way, you also mask your IP address.

Level 2 tries to create a unique fingerprint for each site (for each browser session), FPD tries to detect fingerprinting attempt and preventing scripts to upload the fingerprint or store it in local storages. If you are concerned with fingerprinting, please, use these two techniques. Currently, this is the best protection that you can get from JSR/JShelter in this area.

That being said, we are reaching the Evaluation phase of the NLNet project and both reevaluation of the level3 wrappers for WebGL and removal of level 1 and 3 are a possible directions.

Before we close this issue, we should also re-read all texts and check that level 3 (if we keep it) is clearly marked for what it is - a tool to limit access to real data, not an anti-fingerprinting tool.

**Comment by Kees1958** [comment]
@polcak 

 I am not concerned about fingerprinting. I am concerned about the fact that your implementation is wrong.

 I repeat: returning fake values for WebGL vendor and renderer for any level of protection is wrong. 

Can't make it any simpler.

**Comment by polcak** [comment]
Well you can't make it any simpler but if you want us to take other action then stated above, you need to explain yourself.

Please clarify, what are your goals, what means do you propose to achieve such goals, what are the advantages and disadvantages of such an approach. Why do you think that your proposal is better than the current status?

**Comment by Kees1958** [comment]
I amm not going into mine is bigger than yours discussion: 

Ask the developer of Trace why he randomised real values for WebGL vendor, ask the developer of Cydec anti-FP why he randomized real  WebGL renderer values.

**Comment by polcak** [comment]
Just to remind you, you came here claiming that you see a bug but did not put any reasoning why.

**Comment by Kees1958** [comment]
Firstly: I came here because one of your team representatives asked me to, 
![image](https://user-images.githubusercontent.com/30925856/149765416-4649cb5b-fa2d-4694-beef-4d78f95faf3f.png)

Secondly: it is not a bug, your extension returns fake values by design for WebGL vendor and renderer

Thirdly: I explained (here and on MT) why it is a bad idea to return fake values for WebGL vendor and renderer, the solution is to return randomized real world values, like two other extensions already do.

**Comment by polcak** [comment]
To clarify, I do not know who Sunkar is. What is MT? What is that good point Sunkar refers to? I updated my previous comment "bug" -> "issue".

The design decision for the moment is to return random strings to return as much entropy as possible. This is subject to be changed in the future (as explained above). The purpose for L2 is to have a different fingerprint value on different websites and different sessions. (Atm) I do not have any data if using completely random strings or real-world values is better or worse and from which point of view (but see the next paragraph). You seemed to have some data, so if you have some, please, let us know.

Yes, we do know that using completely random strings might reveal that the user has an active JShelter (or another) extension that employs such a counter-measure. But there are likely to be other measures to detect that. We want to try and close (if possible) such leaks in the future.

**Comment by Kees1958** [comment]
MT = MalwareTips.com Sunkar is a nickname he posted this
![image](https://user-images.githubusercontent.com/30925856/149780855-384e6813-ab39-40df-a669-d324b9cec3ab.png)

**Comment by Kees1958** [comment]
Polcak said: "Yes, we do know that using completely random strings might reveal that the user has an active JShelter (or another) extension that employs such a counter-measure. But there are likely to be other measures to detect that. We want to try and close (if possible) such leaks in the future."

Great, so why not do the same as two other extensions already did: randomize these specific values with randomized real world values to prevent that.

**Comment by TechnologyClassroom** [comment]
I do not know this [Sunkar](https://malwaretips.com/threads/jshelter-javascript-restrictor.110289/page-3#post-971983) individual as far as I know.  [This](https://malwaretips.com/threads/jshelter-javascript-restrictor.110289/) is the MalwareTips thread mentioned, but not linked in this thread.

**Comment by polcak** [comment]
> Great, so why not do the same as two other extensions already did: randomize these specific values with randomized real world values to prevent that.

We opted to the implementation of Brave (Strict level). As mentioned above, atm we do not have any data which option is in practise better.

Also keep in mind that if we wanted to provide real-values, we would need to keep all information in sync (WebGL and other APIs), otherwise, the server could still learn that the user has a privacy extension active. Also we would need to create a set of values to randomize from which is also a state that can reveal what kind of extension the user installed. We support devices like Android phones, Linux phones, ARM computers, desktop computers and others. So there is a lot of work to be done to apply your proposal. We do not have any data that suggests that the work is worth it and there are many fixes with higher priority.

As mentioned above, the goal of the wrapping measures is not to hide in the herd. Atm we do believe that if you want to achieve this (and I agree that it is a valid strategy), you should use Torbrowser.

> The same applies to the real world data points (time zone and geo location) on which you reduce the accuracy. That is a great implementation. I trust you don't apply cut-offs, but instead randomize the last digits to the user selected levels of aggregation. e.g. 12.46.86 randomly becomes 12.46.33 and 12.46.67 and 12.46.42 and NOT always cut off to 12.46.00.

Geolocation: https://github.com/polcak/jsrestrictor/blob/master/common/wrappingS-GEO.js#L154 So basically, we return a random position in a vicinity. The returned position is the same for each page reload. The current implementation has a downside that with each visited page, the server can learn an additional data point which will quickly reveal the inner square. The implementation of the wrapper predates the implementation of farbling. Re-implementation of Geolocation so that the returned position is the same for every session and every domain is on my todo list. This should likely land in 0.6.x or 0.7.x.

I guess that you mean timestamp wrappers. L1 and L2 only cut decimal places off. L3 cuts off all decimal places and provide random decimal part (that is higher then the last returned value). I think that the L3 implementation should be ported to L2.

**Comment by polcak** [comment]
We do not plan to wrap fonts, see #66 and #140 for reasoning.

**Comment by polcak** [comment]
(Also) based on this issue, I created:

* https://pagure.io/JShelter/webextension/issue/69 (Real-world database of WebGL strings)
* https://pagure.io/JShelter/webextension/issue/68 (the recommended level makes user identifiable and their actions linkable during a browser session, this is intentional and always communicated to users. Even so, we will explore other possibilities like changing the values for every readout)
* https://pagure.io/JShelter/webextension/issue/60 (fonts)
We redesigned values returned by Web GL wrappers and Strict protection (empty strings) aff1785eaa228b8fb2f3bb4f2b08da0721c3e1ca made Recommended level spread more 252ab14faab2b5f7b69a525435b235c356ff2439.
* Level 1 was completely reevaluated, level 3 was partly reevaluated.
* There will be FAQ soon.
* We added explanation to UI about the purpose of each level.

If there are any additional comments, please, go to the separate issues or open a new one. Be specific. Try to provide concrete arguments.
