### ISSUE TITLE
Naive (mass) user: worker is not a constructor

### ISSUE THREAD

**Issue by HomelessPenguin** [polcak/jsrestrictor#207]
## Summary

I receive error "worker is not a constructor" when uploading files to mediafire, and when downloading files on megadownloader.

I am a very naive user. I am not a coder. I was attracted to the JsRestrictor add-on to Firefox because it appeared to be designed for folk like me.

By a process of elimination by disabling all add-ons and adding them one by one, I have found that JsRestrictor is the issue.

I may well not have set it up correctly.

## Setup

Pages affected: [URL/all pages/URLs] mediafire.com/myfiles

JShelter Version: latest version as at today's date

Popup information (open JShelter popup on affected pages:

1. Navigate to a page that you are having trouble with: [URL]
2. Click on the JShelter badge icon.
3. Is JavaScript Shield active? [ON/]
3. Is Network Boundary Shield active? [ON/
3. Is Fingerprint Detector active? [ON/]
4. What fingerprint likelihood does Fingerprint Detector report? none
5. Did Fingerprint Detector produce any notifications, if so, what was the notification? none
6. Click on the `Modify` button next to the JavaScript Shield label.
7. What is the highlighted level button text? Default level (recommended)
8. Click on the `Detail tweaks of JS shield for this site` button.
9. What wrappers were triggered by the page, list them below: perhaps you means "the number of APIs misused for fingerprinting called by the page". There were none. Under the Recommended settings with all of its sliders, everything was zero except for "2" beside "Device memory and CPU" 

[Optional:]

OS: Windows 10
Browser: Firefox
Other extensions that might affect JShelter behaviour: 

## How to reproduce

1. Go to mediafire account
2. Click "Upload" to open a Upload pop-up window for drag and drop
3. Open Windows explorer, select a file
4. Drag and drop onto the Upload landing pop-up
5. Receive "Upload Failed 1 file no uploaded" message.
6. Open the error message, get told "worker is not a constructor"

## Expected result

File to be uploaded (mediafire)
File to download in full, and not stall and hang at 99% (megadownloader)

## Actual result

Error message (mediafire)
Stall/hang at 99% (megadownloader

## Reproducibility

Mediafire works fine on PaleMoon to upload files

## Workarounds

Please try to chage settings for the triggered wrappers. <--- I'm unclear on the "triggered wrapper" concept.

## Have you tried other steps to solve the issue?

Tried another browser. Tried Firefox without Jsrestrictor. Both worked.

## Additional information / notes

I apologise if this just me being really dumb, or me not putting in the required minimum effort on the learning curve.

**Comment by polcak** [comment]
Hello @HomelessPenguin,

Thank you for your feedback. Yes, in ideal world JShelter would be designed for you. Even better, it would work smoothly. Unfortunately, we are not there. See, for example, https://jshelter.org/mv3/ and https://jshelter.org/faq/#what-is-the-current-jshelter-status-is-it-ready-or-is-it-still-a-work-in-progress. I also recommend other FAQ entries but you should at least get familiar with https://jshelter.org/faq/#jshelter-broke-a-page-what-should-i-do.

Now let's go to the issue. Do I interpret the text right that you are reporting problems for two sites?

The first one is https://www.mediafire.com/?
* I have not found "Upload" but I found "Upload files now".
* Then I clicked "Upload files" (there is also Upload button if you happen to land on https://app.mediafire.com/myfiles)
* I selected a file to upload.
* I got a window that reported  "worker is not a constructor" next to the filename of the file I selected in the previous step.
* I changed Web Worker API to Strict, the error changed to "Hash worker failed" (Firefox), Strict works with Brave

The "Hash worker failed error" is related to https://pagure.io/JShelter/webextension/issue/80#comment-852202. The "worker is not a constructor" is caused by JShelter removing the Worker. We discussed these errors at the last meeting. We will try to add some quick fixes like this in Chromium-based browsers. Firefox will not work out of the box until https://pagure.io/JShelter/webextension/issue/80 is fixed.

I was not able to reproduce the megadownloader issue as I miss the URL to visit and steps to reproduce. Please open a new issue with specific steps.

For future bug reports. Be as specific as possible, when we ask for URL, provide URL and not some shortened string. The same goes for other questions.

Does PaleMoon support JShelter?

I'm unclear on the "triggered wrapper" concept. - see https://jshelter.org/faq/#tweak-jss-for-this-domain (You do not need to tweak for https://app.mediafire.com/myfiles as I did that myself (see above).

"Tried another browser." does not help as I do not know what browser, if JShelter was installed etc.

**Comment by polcak** [comment]
WebWorker API will be set to Strict on app.mediafire.com starting from the next release https://github.com/polcak/jsrestrictor/commit/4cdbfcfbe33599e4328dce4b0d273ea0fa533fb0#diff-77fd5481191fa1ce6b6111892943922ecaf406805acd1942d6f7d9507a20fdb2R31
