### ISSUE TITLE
[Question] Compatibility with CanvasBlocker AMO extension

### ISSUE THREAD

**Issue by Cade66** [polcak/jsrestrictor#63]
Hi,

_JSRestrictor_ 0.3.2 and _CanvasBlocker_ 0.3 extensions / Firefox 77.0.1 (x64) / Windows 7 (x64)
Simple question regarding _JSR_'s **_protection against canvas fingerprinting_** (Levels>1) when running the _CanvasBlocker_ extension.

I understand _JSR_ doesn't handle Canvas fingerprinting as _CanvasBlocker_ does, not to mention other possible conflicts I'd be unaware of.
Any particular way to proceed? Are these two extensions basically compatible?

JSR seems most interesting. Thanks for this work and for any advice regarding my wondering!

**Comment by polcak** [comment]
Thaks for the question, it is a subtask of #4.

I am now not sure if (A) CB modifies the content of the canvas or (B) only read data.

As JSR modifies the read data, if (A) is true, then JSR replaces all changes made by CB. If (B) is true then (I suppose that CB uses content scripts) both extensions try to change the same APIs and it is probably race condition which defence mechanism wins. If it is indeed race condition, you may be fingerprintable better as the one who uses both CB and JSR or less because the fingerprinter sees different fingerprints. Which one is correct depends on how smart and how focused the fingerprinter is.

Note that JSR freezes the wrapped APIs to prevent pages from simply deleting the wrapper. If CB does not do this, than even in case (B) JSR should always win.

Also note that browsers do not provide a guarantee that content scripts finish before page scripts starts (#40). So the more extensions that you have are running content scripts, the more likely it is to  see wrappers being injected after the page scripts had a chance to store the original versions of the wrapped APIs. See for example https://www.fit.vutbr.cz/~ipolcak/firefox_csp_bug/nocsp.php if you see that a script early in the body sees an unrounded timestamp value when it should be rounded.

If you want canvas fingerprinting provided by CB and still continue using JSR, you can create your custom levels with Canvas fingerprinting turned off.

**Comment by Cade66** [comment]
Thanks for this detailed explanation. I understand better now.
I'll experiment and remember that indeed custom levels are there to adjust.
